### ISSUE TITLE
Request: Disable PK input every run poetry trade

### ISSUE THREAD

**Issue by geeks121** [beeb/pancaketrade#74] opened 2021-12-20 10:59 UTC
Every time i'm start this bot it always ask Private key.. and for me this annoying ,,
i try to change the code but it failed ,,

i think the best way is to acess .env WALLET_PK as docker do ,,

**Comment by beeb** [comment] 2021-12-20 13:26
Closed as duplicate of https://github.com/beeb/pancaketrade/issues/75

**Closed by beeb** 2021-12-20 13:26 UTC
Labels: enhancement
